## Hough Transforms

## Lines

https://www.youtube.com/watch?v=XRBc_xkZREg

In [30]:
import cv2
import numpy as np

# Cargar la imagen
image = cv2.imread('img/freeway.jpg')
# image = cv2.imread('img/board.jpg')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Aplicar desenfoque para reducir el ruido
blurred = cv2.GaussianBlur(gray, (5, 5), 0)

# Detección de bordes con Canny
edges = cv2.Canny(blurred, 50, 100)

# Aplicar la transformada de Hough para la detección de líneas
lines = cv2.HoughLinesP(edges, rho=1, theta=np.pi/180, threshold=100, minLineLength=100, maxLineGap=10)
# lines = cv2.HoughLinesP(edges, rho=1, theta=np.pi/180, threshold=1, minLineLength=1, maxLineGap=1)

# Dibujar las líneas detectadas
if lines is not None:
    for line in lines:
        print(line)
        x1, y1, x2, y2 = line[0]
        cv2.line(image, (x1, y1), (x2, y2), (0, 255, 0), 2)

# Mostrar la imagen con las líneas detectadas
cv2.imshow("Edges", edges)
cv2.imshow("Líneas detectadas", image)
cv2.waitKey(0)
cv2.destroyAllWindows()


[[ 98  68 105  68]]
[[122  62 126  62]]
[[62 19 63 19]]
[[ 49 111  50 111]]
[[ 58 110  65 110]]
[[224  64 228  64]]
[[58 59 61 59]]
[[204  50 206  48]]
[[125  40 126  40]]
[[288  11 289  11]]
[[64 81 71 80]]
[[91 87 93 87]]
[[310 150 312 150]]
[[101  80 115  76]]
[[166  52 176  52]]
[[43 90 55 87]]
[[54  8 54  7]]
[[209  89 211  88]]
[[198  59 199  57]]
[[83 76 85 76]]
[[193 155 207 155]]
[[206  87 208  86]]
[[228  57 228  56]]
[[233 108 233 107]]
[[ 13 114  15 112]]
[[144  33 146  34]]
[[156  42 156  41]]
[[130  60 133  60]]
[[294  65 295  61]]
[[132  40 133  40]]
[[ 66 152  67 152]]
[[ 58 152  60 152]]
[[111  55 121  56]]
[[295  34 296  31]]
[[20 97 22 96]]
[[62 99 63 99]]
[[ 7 93  9 93]]
[[279  11 279  10]]
[[289  86 291  87]]
[[79 88 95 83]]
[[258 108 264 108]]
[[305  27 305  26]]
[[59  4 65  1]]
[[ 46 106  47 106]]
[[49  6 50  6]]
[[231  68 242  69]]
[[ 61 113  63 113]]
[[ 12 136  14 136]]
[[164  60 164  57]]
[[19  7 22  7]]
[[117 114 119 114]]
[[94 73 98 73]]
[[295  30 295  29]]


In [7]:
import cv2
import numpy as np

# Iniciar la captura de video desde la cámara
cap = cv2.VideoCapture(0)

while True:
    # Leer el frame de la cámara
    ret, frame = cap.read()
    if not ret:
        break

    # Convertir el frame a escala de grises
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Aplicar desenfoque para reducir el ruido
    blurred = cv2.GaussianBlur(gray, (5, 5), 0)

    # Detección de bordes con Canny
    edges = cv2.Canny(blurred, 50, 150)

    # Aplicar la transformada de Hough para la detección de líneas
    lines = cv2.HoughLinesP(edges, rho=1, theta=np.pi/180, threshold=100, minLineLength=100, maxLineGap=10)

    # Dibujar las líneas detectadas en el frame
    if lines is not None:
        for line in lines:
            x1, y1, x2, y2 = line[0]
            cv2.line(frame, (x1, y1), (x2, y2), (0, 255, 0), 2)

    # Mostrar el frame con las líneas detectadas
    cv2.imshow("Líneas en tiempo real", frame)

    # Salir del loop si se presiona la tecla 'q'
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

# Liberar la captura de video y cerrar ventanas
cap.release()
cv2.destroyAllWindows()


## Circles

In [5]:
import cv2
import numpy as np

# Leer la imagen y convertirla a gris
image = cv2.imread('img/circle.png')
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Aplicar el filtro Gaussiano
blurred = cv2.GaussianBlur(gray, (9, 9), 2)

# Detectar círculos
circles = cv2.HoughCircles(blurred, cv2.HOUGH_GRADIENT, dp=1.2, minDist=50, param1=50, param2=30, minRadius=10, maxRadius=100)

# Convertir las coordenadas de los círculos al formato entero
if circles is not None:
    circles = np.round(circles[0, :]).astype("int")

    # Dibujar los círculos en la imagen original
    for (x, y, r) in circles:
        cv2.circle(image, (x, y), r, (0, 255, 0), 4)
        cv2.rectangle(image, (x - 5, y - 5), (x + 5, y + 5), (0, 128, 255), -1)

cv2.imshow('Detected Circles', image)
cv2.waitKey(0)
cv2.destroyAllWindows()


In [38]:
import numpy as np
import cv2 as cv
 
img = cv.imread('img/circle.png', cv.IMREAD_GRAYSCALE)
assert img is not None, "file could not be read, check with os.path.exists()"
img = cv.medianBlur(img,5)
cimg = cv.cvtColor(img,cv.COLOR_GRAY2BGR)
 
circles = cv.HoughCircles(img,cv.HOUGH_GRADIENT,1,20,
                            param1=50,param2=30,minRadius=0,maxRadius=0)
 
circles = np.uint16(np.around(circles))

print(circles)

for i in circles[0,:]:
    # ! (X, Y, R)
    # draw the outer circle
    cv.circle(cimg,(i[0],i[1]),i[2],(0,255,0),2)
    # draw the center of the circle
    cv.circle(cimg,(i[0],i[1]),2,(0,0,255),3)
 
cv.imshow('detected circles',cimg)
cv.waitKey(0)
cv.destroyAllWindows()

[[[128 128  75]]]


In [36]:
import cv2
import numpy as np

# Abrir el archivo de video
cap = cv2.VideoCapture('img/Conveyor Belt Top.mp4')

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Convertir a escala de grises
    gray_image = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Aplicar un filtro Gaussiano para suavizar la imagen y reducir el ruido
    blurred_image = cv2.GaussianBlur(gray_image, (9, 9), 2)

    # Detectar círculos usando la Transformada de Hough
    circles = cv2.HoughCircles(
        blurred_image,
        cv2.HOUGH_GRADIENT,  # Método de detección
        dp=1,  # Relación de resolución
        minDist=20,  # Distancia mínima entre centros de círculos
        param1=50,  # Primer parámetro de la detección de Canny
        param2=30,  # Umbral de acumulación para la detección de círculos
        minRadius=10,  # Radio mínimo del círculo a detectar
        maxRadius=100  # Radio máximo del círculo a detectar
    )

    if circles is not None:
        # Convertir coordenadas de círculos a enteros
        # print(circles[0, :])
        circles = np.round(circles[0, :]).astype("int")
        for (x, y, r) in circles:
            # Dibujar el círculo en la imagen original
            cv2.circle(frame, (x, y), r, (0, 255, 0), 4)
            # Dibujar el centro del círculo
            cv2.circle(frame, (x, y), 2, (0, 0, 255), 3)

    # Mostrar el marco procesado
    cv2.imshow('Detected Circles', frame)

    # Salir si se presiona la tecla 'q'
    if cv2.waitKey(10) == ord('q'):
        break

# Liberar recursos
cap.release()
cv2.destroyAllWindows()


[[ 37.5 666.5  66.3]]
[[ 74.5 667.5  73. ]
 [ 98.5 656.5  80.1]]
[[113.5 666.5  73.9]]
[[151.5 667.5  73.2]
 [174.5 657.5  78.9]]
[[192.5 668.5  74.3]]
[[233.5 665.5  75.1]]
[[275.5 667.5  74.8]]


# Homework

In [32]:
import cv2
import numpy as np

# Abrir el archivo de video
cap = cv2.VideoCapture('img/driving_video.mp4')

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    height = frame.shape[0]
    width = frame.shape[1]

    region_of_interest_vertices = [
        (0, height),
        (width / 2, height / 1.4), # 1.4 best value
        (width, height),
    ]
    
    # Convertir a escala de grises
    gray_image = cv2.cvtColor(frame, cv2.COLOR_RGB2GRAY)
    

    gray_image = cv2.GaussianBlur(gray_image, (5,5), 0.1)
    cv2.imshow('Gray Image', gray_image)

    # Crear una imagen en color para dibujar los puntos de interés
    gray_with_points = cv2.cvtColor(gray_image, cv2.COLOR_GRAY2RGB)

    colors = ((255,0,0), (0,255,0), (0,0,255))
    # Dibujar los puntos de interés en rojo
    for i, vertex in enumerate(region_of_interest_vertices):
        cv2.circle(gray_with_points, (int(vertex[0]), int(vertex[1])), 10, colors[i], -1)  # -1 rellena el círculo
    
    cv2.imshow('Gray Image with Points', gray_with_points)

    # Aplicar detección de bordes Canny
    canny_image = cv2.Canny(gray_image, 100, 120)
    cv2.imshow('Canny Image', canny_image)
    
    # Aplicar la región de interés
    mask = np.zeros_like(canny_image)
    cv2.fillPoly(mask, np.array([region_of_interest_vertices], np.int32), 255)
    cropped_image = cv2.bitwise_and(canny_image, mask)
    cv2.imshow('Cropped Image', mask)
    
    
    # Detectar líneas usando la Transformada de Hough
    lines = cv2.HoughLinesP(cropped_image,
                            rho=2,
                            theta=np.pi / 180,
                            threshold=50,
                            lines=np.array([]),
                            minLineLength=40,
                            maxLineGap=100)
    
    # Dibujar líneas en la imagen original
    img_with_lines = np.copy(frame)
    blank_image = np.zeros((img_with_lines.shape[0], img_with_lines.shape[1], 3), dtype=np.uint8)

    

    if lines is not None:
        for line in lines:
            for x1, y1, x2, y2 in line:
                cv2.line(blank_image, (x1, y1), (x2, y2), (0, 255, 0), thickness=3)

    cv2.imshow("blank", blank_image)
    
    img_with_lines = cv2.addWeighted(img_with_lines, 0.8, blank_image, 0.5, 0.0)
    
    # Mostrar el marco procesado
    cv2.imshow('Processed Frame', img_with_lines)
    
    # Salir si se presiona la tecla 'q'
    if cv2.waitKey(10) == ord('q'):
        break

# Liberar recursos
cap.release()
cv2.destroyAllWindows()
